export default {
    'Elements - Checkbox': '#checkbox',
    'Elements - Classtest': '#classTest',
    'Elements - Message 1': '#message1',
    'Elements - Message 2': '#message2',
    'Elements - Toggle Background': '#toggleBackground',
    'Elements - Draggable': '#draggable',
    'Elements - Droppable': '#droppable',
    'Elements - Non Existing': '#noneExisting',
    'Elements - Existing': '#existing',
    'Elements - Square 100x100px': '#square100x100',
    'Elements - Hidden': '#hidden',
    'Elements - Displayed': '#visible',
    'Elements - Make Displayed': '#makeVisible',
    'Elements - Make Invisible': '#makeInvisible',
    'Elements - Button Make Displayed': '#btnMakeVisible',
    'Elements - Button Make Invisible': '#btnMakeInvisible',
    'Elements - Footer': '#footer',
    'Elements - Footer Alias': 'footer',
    'Elements - Heading': 'h1',
    'Elements - Second Heading': 'h1:nth-child(n+2)',
    'Elements - Subtitle': '.subtitle',
    'Elements - Text Input': '#textinput',
    'Elements - Form Submit': '#formSubmitTest > button',
    'Elements - Form Submit Message': '#formSubmitTest .message',
    'Elements - Test Input': '#testInput',
    'Elements - Move To': '#moveTo',
    'Elements - Link Same Window': '#linkSameWindow',
    'Elements - Link New Window': '#linkNewWindow',
    'Elements - Test Key Response': '#testKeyResponse',
    'Elements - Attribute Comparison': '#attributeComparison',
    'Elements - CSS Attribute Comparison': '#cssAttributeComparison',
    'Elements - Toggle Message': '#toggleMessage',
    'Elements - Body': 'body',
    'Elements - Navigate To example.com Link': '#testClick',
};
