export default {
    'Text Comparison - Text 1': '#textComparison1',
    'Text Comparison - Text 2': '#textComparison2',
    'Text Comparison - Text 3': '#textComparison3',
    'Text Comparison - Text 4': '#textComparison4',
    'Text Comparison - Text 5': '#textComparison5',
    'Text Comparison - Text 6': '#textComparison6',
    'Text Comparison - Text 7': '#textComparison7',
    'Text Comparison - Text 8': '#textComparison8',
    'Text Comparison - Text 9': '#textComparison9',
    'Text Comparison - Text Without Cucumber': '#textDoesNotContainCucumber',
    'Text Comparison - Text With Cucumber': '#textDoesContainCucumber',
    'Text Comparison - Value Without Cucumber': '#valueDoesNotContainCucumber',
    'Text Comparison - Value With Cucumber': '#valueDoesContainCucumber',
    'Text Comparison - Button Wait For Checked': 'button[id=\'waitForCheckedBtn\']',
};
