export default {
    'Wait For - Enabled - Element': '#waitForEnabledElement',
    'Wait For - Enabled - Button': '#waitForEnabledBtn',
    'Wait For - Selected - Element': '#waitForSelectedElement option:nth-child(2)',
    'Wait For - Selected - Button': '#waitForSelectedBtn',
    'Wait For - Checked - Element': '#waitForCheckedElement',
    'Wait For - Checked - Button': '#waitForCheckedBtn',
    'Wait For - Displayed - Element': '#waitForVisibleElement',
    'Wait For - Displayed - Button': '#waitForVisibleBtn',
    'Wait For - Contains Text - Element': '#waitForContainsTextElement',
    'Wait For - Contains Text - Button': '#waitForContainsTextBtn',
    'Wait For - Contains Value - Element': '#waitForContainsValueElement',
    'Wait For - Contains Value - Button': '#waitForContainsValueBtn',
    'Wait For - Create - Element': '#waitForCreateElement > span',
    'Wait For - Create - Button': '#waitForCreateBtn',
};
